# Numpy 
### **[Reference](https://numpy.org/doc/)**

In [1]:
import sys
sys.executable

'c:\\users\\rishabh rathore\\appdata\\local\\programs\\python\\python39\\python.exe'

In [2]:
# !pip install numpy
import numpy as np

In [3]:
arr = np.array([[2,4,6,8,10,12],[1,3,5,7,9,11]],dtype ='int32')
print(arr)

[[ 2  4  6  8 10 12]
 [ 1  3  5  7  9 11]]


In [4]:
arr.ndim #dimensions

2

In [5]:
arr.shape # For a matrix with n rows and m columns, shape will be (n,m)

(2, 6)

In [6]:
arr.size # the total number of elements of the array.

12

In [7]:
arr.dtype

dtype('int32')

In [8]:
type(arr) # it is the python syntax

numpy.ndarray

In [9]:
arr.itemsize # the size in bytes of each element of the array

4

In [10]:
num = np.array([[10,20,40],[40,80,160]],dtype=complex)

In [11]:
num

array([[ 10.+0.j,  20.+0.j,  40.+0.j],
       [ 40.+0.j,  80.+0.j, 160.+0.j]])

In [12]:
arr.itemsize

4

### Array Creation

In [13]:
arr = np.array([2,3,4])

In [14]:
arr

array([2, 3, 4])

In [15]:
arr_complex = np.array([20,30,40],dtype=complex)
arr_complex

array([20.+0.j, 30.+0.j, 40.+0.j])

### Zeros

In [16]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
num = [10,20,30,40,50,60]
np.zeros_like(num)

array([0, 0, 0, 0, 0, 0])

In [97]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [99]:
arr = np.ones((2,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [100]:
arr +5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [102]:
arr*4

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [105]:
np.empty((3,4))

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [110]:
np.eye(5) # defines a 2D identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [112]:
np.diag([10,20,30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [114]:
np.random.rand(2,3)

array([[0.27348036, 0.2228581 , 0.33233937],
       [0.61092422, 0.2489183 , 0.45063635]])

In [115]:
np.random.randn(2,3)

array([[ 1.39575009,  0.13799284, -0.01563516],
       [ 0.31498608, -0.51789892, -0.45121599]])

In [120]:
nums = np.random.randint(2,10,(3,4))
nums

array([[6, 2, 2, 8],
       [8, 2, 2, 7],
       [2, 3, 5, 3]])

In [121]:
import pandas as pd

In [122]:
pd.DataFrame(nums)

0  1  2  3
0  6  2  2  8
1  8  2  2  7
2  2  3  5  3

In [125]:
print(nums)
nums.shape

[[6 2 2 8]
 [8 2 2 7]
 [2 3 5 3]]


(3, 4)

In [124]:
nums.reshape(4,3)

array([[6, 2, 2],
       [8, 8, 2],
       [2, 7, 2],
       [3, 5, 3]])

In [127]:
nums.reshape(4,-1)

array([[6, 2, 2],
       [8, 8, 2],
       [2, 7, 2],
       [3, 5, 3]])

In [126]:
nums.reshape(6,2)

array([[6, 2],
       [2, 8],
       [8, 2],
       [2, 7],
       [2, 3],
       [5, 3]])

In [130]:
nums.reshape(2,3,2)

array([[[6, 2],
        [2, 8],
        [8, 2]],

       [[2, 7],
        [2, 3],
        [5, 3]]])

### Arange function

In [18]:
list(range(5))

[0, 1, 2, 3, 4]

In [19]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
# list(range(0.4,10.4)) #TypeError: 'float' object cannot be interpreted as an integer

In [21]:
np.arange(0.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

### Linspace

In [22]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

### Logspace

In [23]:
np.logspace(1,5,20,base=4)

array([   4.        ,    5.3556164 ,    7.17065677,    9.60082176,
         12.85457963,   17.21104938,   23.0439446 ,   30.85363193,
         41.31005433,   55.31020117,   74.05505519,   99.15261711,
        132.75584569,  177.74734625,  237.98665088,  318.6413029 ,
        426.63014728,  571.21685389,  764.80458837, 1024.        ])

In [24]:
np.logspace(1,5,10) # default base=10.0

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [25]:
np.logspace(1,5,10,base=2) 

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [26]:
np.add(222,223)

445

In [27]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [29]:
arr.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [30]:
arr*arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [31]:
arr+arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [32]:
arr%arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
arr/arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
2/arr

array([[2.        , 1.        , 0.66666667, 0.5       ],
       [0.4       , 0.33333333, 0.28571429, 0.25      ]])

In [35]:
np.empty((2,6))

array([[1.13945490e-311, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000, 4.00766127e+175, 8.60952352e-072],
       [5.49606416e-090, 1.56082907e+161, 3.63373968e+174,
        3.05999123e-057, 6.48224660e+170, 4.93432906e+257]])

In [36]:
arr1 = np.arange(0,100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
arr1.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
arr1.shape

(100,)

In [40]:
arr1.sum()

4950

In [41]:
array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
array.sum(axis=0)

array([22, 26, 30])

In [43]:
array.sum(axis=1)

array([ 6, 15, 24, 33])

In [44]:
array.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [45]:
array.flat
for i in array.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [46]:
array.ndim #Dimensions 

2

In [47]:
array.size #size

12

In [48]:
array.nbytes #Storage in bytes

48

In [49]:
array.max() #maxValue

12

In [50]:
array.min() #minValue

1

In [51]:
array.argmax() #maxValueIndx

11

In [52]:
array.argmin() #minValueIndx

0

In [53]:
array.argsort() # sort the array acc. to index value

test = np.array([2,34,56,4,56])
test.argsort()

array([0, 3, 1, 2, 4], dtype=int64)

In [54]:
array.argmax(axis=0)

array([3, 3, 3], dtype=int64)

In [55]:
array.argmin(axis=1)

array([0, 0, 0, 0], dtype=int64)

In [56]:
np.sqrt(array)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [57]:
np.where(array>10)

(array([3, 3], dtype=int64), array([1, 2], dtype=int64))

In [58]:
np.count_nonzero(array)

12

In [59]:
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [60]:
np.nonzero(array)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [61]:
np.imag(array)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
np.real(array)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
array.itemsize

4

In [64]:
array.itemsize * array.size 

48

In [65]:
array.compress

<function ndarray.compress>

In [66]:
array.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [67]:
array.view()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Slicing

In [68]:
arr[0,1]

2

In [69]:
arr1 = np.array([2,4,6,8,10])

In [70]:
arr1[2:4]

array([6, 8])

In [71]:
arr2 = arr1[:5].copy()

In [72]:
arr2

array([ 2,  4,  6,  8, 10])

In [143]:
nums1 = np.random.randint(1,10,(5,6))
nums1

array([[3, 5, 1, 9, 2, 7],
       [1, 5, 1, 9, 4, 7],
       [8, 7, 7, 4, 2, 1],
       [2, 2, 2, 9, 1, 7],
       [4, 5, 6, 6, 7, 2]])

In [144]:
nums1>8

array([[False, False, False,  True, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False, False]])

In [145]:
nums1[nums1>7]

array([9, 9, 8, 9])

In [146]:
nums1

array([[3, 5, 1, 9, 2, 7],
       [1, 5, 1, 9, 4, 7],
       [8, 7, 7, 4, 2, 1],
       [2, 2, 2, 9, 1, 7],
       [4, 5, 6, 6, 7, 2]])

In [151]:
nums1[2,[0,1,2]]

array([8, 7, 7])

In [153]:
nums1[2:4,[2,3]]

array([[7, 4],
       [2, 9]])

### Matrix Multiplication

In [158]:
num1 = np.random.randint(1,10,(3,4))
num1

array([[5, 7, 3, 4],
       [3, 8, 3, 4],
       [7, 7, 2, 9]])

In [159]:
num2 = np.random.randint(1,10,(4,3))
num2

array([[1, 7, 9],
       [2, 9, 8],
       [6, 6, 5],
       [8, 1, 5]])

In [161]:
num1@num2

array([[ 69, 120, 136],
       [ 69, 115, 126],
       [105, 133, 174]])

In [162]:
num1.dot(num2)

array([[ 69, 120, 136],
       [ 69, 115, 126],
       [105, 133, 174]])

In [164]:
num1/num1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Deep copy and Shallow copy

In [73]:
a = []
b = []

In [74]:
a==b

True

In [75]:
a is b

False

In [76]:
a = [10,20,30,40]

In [77]:
arr = a #shallow copy

In [78]:
arr[0] = 100

In [79]:
a[0]

100

In [80]:
a is arr

True

In [81]:
id(a) == id(arr)

True

In [82]:
id(a)

2304403600704

In [83]:
id(arr)

2304403600704

In [84]:
b = arr.copy() # deep copy

In [85]:
b[0] = 200

In [86]:
arr[0]

100

In [87]:
b[0]

200

In [88]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [89]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [90]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [91]:
iterable = (i*i for i in range(5))

In [92]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [93]:
np.fromstring('23 46 56 67',dtype = int,sep=' ')

array([23, 46, 56, 67])

### Broadcasting

In [168]:
arr = np.zeros((3,4))

In [169]:
arr +5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [171]:
a = np.array([1,2,3,4])
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [174]:
b = np.array([[3,4,5]])

In [178]:
arr1 = arr + b.T
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [176]:
b.T

array([[3],
       [4],
       [5]])

In [179]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

### Array Manipulation

In [180]:
num = np.random.randint(1,10,(4,4))

In [181]:
num

array([[8, 4, 8, 1],
       [5, 9, 7, 1],
       [1, 6, 1, 2],
       [8, 4, 7, 4]])

In [182]:
num.reshape(8,2)

array([[8, 4],
       [8, 1],
       [5, 9],
       [7, 1],
       [1, 6],
       [1, 2],
       [8, 4],
       [7, 4]])

In [183]:
num.reshape(2,2,4)

array([[[8, 4, 8, 1],
        [5, 9, 7, 1]],

       [[1, 6, 1, 2],
        [8, 4, 7, 4]]])

In [184]:
num

array([[8, 4, 8, 1],
       [5, 9, 7, 1],
       [1, 6, 1, 2],
       [8, 4, 7, 4]])

In [185]:
num.T

array([[8, 5, 1, 8],
       [4, 9, 6, 4],
       [8, 7, 1, 7],
       [1, 1, 2, 4]])

In [186]:
num.flatten()

array([8, 4, 8, 1, 5, 9, 7, 1, 1, 6, 1, 2, 8, 4, 7, 4])

In [192]:
np.expand_dims(num,axis=1)

array([[[8, 4, 8, 1]],

       [[5, 9, 7, 1]],

       [[1, 6, 1, 2]],

       [[8, 4, 7, 4]]])

In [193]:
np.expand_dims(num,axis=0)

array([[[8, 4, 8, 1],
        [5, 9, 7, 1],
        [1, 6, 1, 2],
        [8, 4, 7, 4]]])

In [194]:
data = np.array([[1],[2],[3]])

In [195]:
np.squeeze(data)

array([1, 2, 3])

In [196]:
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [197]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [199]:
np.diag([1,2,4])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 4]])

### Binary Operators

In [201]:
ar1 = np.random.randint(1,10,(3,4))
ar2 = np.random.randint(1,10,(3,4))

In [203]:
ar1 + ar2

array([[13,  7, 11, 10],
       [ 6, 13,  6,  8],
       [10, 14, 13,  3]])

In [204]:
ar1 * ar2

array([[42, 12, 28, 24],
       [ 5, 36,  8, 12],
       [24, 48, 42,  2]])

In [205]:
ar1 / ar2

array([[1.16666667, 1.33333333, 0.57142857, 1.5       ],
       [5.        , 2.25      , 2.        , 3.        ],
       [1.5       , 0.75      , 1.16666667, 2.        ]])

In [206]:
ar1 - ar2

array([[ 1,  1, -3,  2],
       [ 4,  5,  2,  4],
       [ 2, -2,  1,  1]])

In [207]:
ar1 % ar2

array([[1, 1, 4, 2],
       [0, 1, 0, 0],
       [2, 6, 1, 0]])

In [208]:
ar1 // ar2

array([[1, 1, 0, 1],
       [5, 2, 2, 3],
       [1, 0, 1, 2]])

In [209]:
ar1 ** ar2

array([[ 117649,      64,   16384,    1296],
       [      5,    6561,      16,      36],
       [   1296, 1679616,  117649,       2]])

In [210]:
~ar1

array([[ -8,  -5,  -5,  -7],
       [ -6, -10,  -5,  -7],
       [ -7,  -7,  -8,  -3]])

In [211]:
ar1 ^ ar2

array([[ 1,  7,  3,  2],
       [ 4, 13,  6,  4],
       [ 2, 14,  1,  3]])

In [212]:
ar1 & ar2

array([[6, 0, 4, 4],
       [1, 0, 0, 2],
       [4, 0, 6, 0]])

In [216]:
ar1>ar2

array([[ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True]])

### String Functions.

In [218]:
names = np.array(['Ram','Jhon','Jone','Suraj'])

In [219]:
names

array(['Ram', 'Jhon', 'Jone', 'Suraj'], dtype='<U5')

In [221]:
np.char.upper(names)

array(['RAM', 'JHON', 'JONE', 'SURAJ'], dtype='<U5')

In [228]:
np.char.capitalize(names)

array(['Ram', 'Jhon', 'Jone', 'Suraj'], dtype='<U5')

In [229]:
np.char.title(names)

array(['Ram', 'Jhon', 'Jone', 'Suraj'], dtype='<U5')

### Mathematical Functions

In [231]:
ar1

array([[7, 4, 4, 6],
       [5, 9, 4, 6],
       [6, 6, 7, 2]])

In [233]:
np.sin(ar1)

array([[ 0.6569866 , -0.7568025 , -0.7568025 , -0.2794155 ],
       [-0.95892427,  0.41211849, -0.7568025 , -0.2794155 ],
       [-0.2794155 , -0.2794155 ,  0.6569866 ,  0.90929743]])

In [235]:
np.cos(ar1)

array([[ 0.75390225, -0.65364362, -0.65364362,  0.96017029],
       [ 0.28366219, -0.91113026, -0.65364362,  0.96017029],
       [ 0.96017029,  0.96017029,  0.75390225, -0.41614684]])

In [236]:
np.sin(ar1) / np.cos(ar1)

array([[ 0.87144798,  1.15782128,  1.15782128, -0.29100619],
       [-3.38051501, -0.45231566,  1.15782128, -0.29100619],
       [-0.29100619, -0.29100619,  0.87144798, -2.18503986]])

In [234]:
np.tan(ar1)

array([[ 0.87144798,  1.15782128,  1.15782128, -0.29100619],
       [-3.38051501, -0.45231566,  1.15782128, -0.29100619],
       [-0.29100619, -0.29100619,  0.87144798, -2.18503986]])

In [237]:
np.log10(ar1)

array([[0.84509804, 0.60205999, 0.60205999, 0.77815125],
       [0.69897   , 0.95424251, 0.60205999, 0.77815125],
       [0.77815125, 0.77815125, 0.84509804, 0.30103   ]])

In [238]:
np.log2(ar1)

array([[2.80735492, 2.        , 2.        , 2.5849625 ],
       [2.32192809, 3.169925  , 2.        , 2.5849625 ],
       [2.5849625 , 2.5849625 , 2.80735492, 1.        ]])

In [239]:
np.exp(ar1)

array([[1.09663316e+03, 5.45981500e+01, 5.45981500e+01, 4.03428793e+02],
       [1.48413159e+02, 8.10308393e+03, 5.45981500e+01, 4.03428793e+02],
       [4.03428793e+02, 4.03428793e+02, 1.09663316e+03, 7.38905610e+00]])

In [241]:
np.exp2(ar1) #Calculate 2**p for all p in the input array.

array([[128.,  16.,  16.,  64.],
       [ 32., 512.,  16.,  64.],
       [ 64.,  64., 128.,   4.]])

In [244]:
np.power(ar1,2)

array([[49, 16, 16, 36],
       [25, 81, 16, 36],
       [36, 36, 49,  4]], dtype=int32)

In [245]:
np.mean(ar1)

5.5

In [246]:
np.median(ar1)

6.0

In [249]:
np.std(ar1)

1.7559422921421233

In [250]:
np.var(ar1)

3.0833333333333335

In [252]:
np.max(ar1)

9

In [253]:
np.min(ar1)

2

### Arithmetic Operations.

In [255]:
np.add(10,30)

40

In [260]:
np.add(ar1,ar2)

array([[13,  7, 11, 10],
       [ 6, 13,  6,  8],
       [10, 14, 13,  3]])

In [259]:
np.subtract(299,239)

60

In [261]:
np.subtract(ar1,ar2)

array([[ 1,  1, -3,  2],
       [ 4,  5,  2,  4],
       [ 2, -2,  1,  1]])

In [257]:
np.sum([10,30,230,230,30,20])

550

In [262]:
np.sum(ar1)

66

In [263]:
np.multiply(20,34)

680

In [264]:
np.multiply(ar1,ar2)

array([[42, 12, 28, 24],
       [ 5, 36,  8, 12],
       [24, 48, 42,  2]])

In [266]:
np.mod(243,7)

5

In [267]:
np.mod(ar1,ar2)

array([[1, 1, 4, 2],
       [0, 1, 0, 0],
       [2, 6, 1, 0]])

In [268]:
np.square(ar1)

array([[49, 16, 16, 36],
       [25, 81, 16, 36],
       [36, 36, 49,  4]])

### Sort, Search & Counting Functions.

In [274]:
data = np.array([2,5,6,3,5,7,8,9,12])

In [275]:
np.sort(data)

array([ 2,  3,  5,  5,  6,  7,  8,  9, 12])

In [276]:
data

array([ 2,  5,  6,  3,  5,  7,  8,  9, 12])

In [280]:
np.searchsorted(data,6)

5

In [283]:
data1 =  np.array([0,232,0,0,0,1,2,34,4,45,3])
len(data1)

11

In [282]:
np.count_nonzero(data1)

7

In [285]:
np.where(data1>10)

(array([1, 7, 9], dtype=int64),)

In [289]:
np.extract(data1>2,data1)

array([232,  34,   4,  45,   3])

### Copies and Views

In [301]:
num = np.array([1,2,3,5,10])

In [302]:
t = np.copy(num)

In [303]:
t[0] = 10

In [304]:
num[0]

1

In [305]:
t[0]

10

In [306]:
u = num.view()

In [307]:
u

array([ 1,  2,  3,  5, 10])

In [308]:
u[0] = 14

In [309]:
u[0]

14

In [310]:
num[0]

14

In [314]:
u

array([14,  2,  3,  5, 10])

In [316]:
num

array([14,  2,  3,  5, 10])

### Matrix library

In [319]:
import numpy.matlib as nm

In [322]:
nm.zeros((2,4))

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [321]:
nm.ones((2,5))

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [323]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

### Linear Algebra

In [324]:
ar1

array([[7, 4, 4, 6],
       [5, 9, 4, 6],
       [6, 6, 7, 2]])

In [325]:
ar2

array([[6, 3, 7, 4],
       [1, 4, 2, 2],
       [4, 8, 6, 1]])

In [327]:
ar1.dot(ar2.T)

array([[106,  43,  90],
       [109,  61, 122],
       [111,  48, 116]])