# Numpy 
### **[Reference](https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html)**

In [3]:
import sys
sys.executable

'c:\\Users\\RISHABH RATHORE\\AppData\\Local\\Programs\\Python\\Python39\\python.exe'

In [5]:
# !pip install numpy
import numpy as np

In [2]:
arr = np.array([[2,4,6,8,10,12],[1,3,5,7,9,11]],dtype ='int32')
print(arr)

[[ 2  4  6  8 10 12]
 [ 1  3  5  7  9 11]]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(2, 6)

In [5]:
arr.dtype

dtype('int32')

In [6]:
np.add(222,223)

445

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((2,6)).dtype

dtype('float64')

In [9]:
arr_rng = np.arange(10)
arr_rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
lspace = np.linspace(1,10,4)
lspace

array([ 1.,  4.,  7., 10.])

In [11]:
np.ones(6).dtype

dtype('float64')

In [12]:
arr.T

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9],
       [12, 11]])

In [13]:
arr*arr

array([[  4,  16,  36,  64, 100, 144],
       [  1,   9,  25,  49,  81, 121]])

In [14]:
arr+arr

array([[ 4,  8, 12, 16, 20, 24],
       [ 2,  6, 10, 14, 18, 22]])

In [15]:
arr%arr

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [16]:
arr/arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
2/arr

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667],
       [2.        , 0.66666667, 0.4       , 0.28571429, 0.22222222,
        0.18181818]])

In [18]:
np.empty((2,6))

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667],
       [2.        , 0.66666667, 0.4       , 0.28571429, 0.22222222,
        0.18181818]])

In [19]:
arr1 = np.arange(100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
arr1.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [21]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
arr1.shape

(100,)

In [23]:
arr1.sum()

4950

In [24]:
array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
array.sum(axis=0)

array([22, 26, 30])

In [26]:
array.sum(axis=1)

array([ 6, 15, 24, 33])

In [27]:
array.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [28]:
array.flat
for i in array.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [29]:
array.ndim #Dimensions 

2

In [30]:
array.size #size

12

In [31]:
array.nbytes #Storage in bytes

48

In [32]:
array.max() #maxValue

12

In [33]:
array.min() #minValue

1

In [34]:
array.argmax() #maxValueIndx

11

In [35]:
array.argmin() #minValueIndx

0

In [36]:
array.argsort() # sort the array acc. to index value

test = np.array([2,34,56,4,56])
test.argsort()

array([0, 3, 1, 2, 4], dtype=int64)

In [37]:
array.argmax(axis=0)

array([3, 3, 3], dtype=int64)

In [38]:
array.argmin(axis=1)

array([0, 0, 0, 0], dtype=int64)

In [39]:
np.sqrt(array)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [40]:
np.where(array>10)

(array([3, 3], dtype=int64), array([1, 2], dtype=int64))

In [41]:
np.count_nonzero(array)

12

In [42]:
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
np.nonzero(array)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [44]:
np.imag(array)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
np.real(array)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
array.itemsize

4

In [47]:
array.itemsize * array.size 

48

In [48]:
array.compress

<function ndarray.compress>

In [49]:
array.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [50]:
array.view()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Slicing

In [51]:
arr[0,1]

4

In [52]:
arr1 = np.array([2,4,6,8,10])

In [53]:
arr1[2:4]

array([6, 8])

In [54]:
arr2 = arr1[:5].copy()

In [55]:
arr2

array([ 2,  4,  6,  8, 10])