### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Import Numpy

In [ ]:
# !pip install numpy
import numpy as np

### Creating Numpy Arrays

In [5]:
# np.array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
odds = np.array([1,3,5,7,9])
odds

array([1, 3, 5, 7, 9])

In [6]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
even = np.array([[2,4,6],[8,10,12],[14,16,18]])
even

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
#  3D array / tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [17]:
# np.arange
np.arange(1,11,2,dtype = float)

array([1., 3., 5., 7., 9.])

In [21]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [29]:
np.arange(1,37).reshape(4,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

In [30]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [47]:
# np.ones 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.ones((2,2),dtype = bool)

array([[ True,  True],
       [ True,  True]])

In [34]:
# np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
# np.random
np.random.random((3,4))

array([[0.12138666, 0.96606577, 0.59061355, 0.10743898],
       [0.97912534, 0.62807397, 0.5744694 , 0.89662164],
       [0.37477991, 0.84372872, 0.78797116, 0.79292614]])

In [80]:
np.random.random((1,10,1))

array([[[0.8542661 ],
        [0.42202248],
        [0.57057702],
        [0.05850614],
        [0.44478269],
        [0.81884574],
        [0.97317222],
        [0.36230355],
        [0.63468509],
        [0.77715566]]])

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [39]:
np.linspace(-10,10,15)
# 1. Lower Range 2. Upper Range 3. Number of items

array([-10.        ,  -8.57142857,  -7.14285714,  -5.71428571,
        -4.28571429,  -2.85714286,  -1.42857143,   0.        ,
         1.42857143,   2.85714286,   4.28571429,   5.71428571,
         7.14285714,   8.57142857,  10.        ])

In [40]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Array Attributes

In [63]:
A1 = np.arange(10,dtype=np.int32)
A2 = np.arange(12,dtype=float).reshape(3,4)
A3 = np.arange(8).reshape(2,2,2)
A3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [49]:
# ndim
A1.ndim

1

In [51]:
A2.ndim

2

In [52]:
A3.ndim

3

In [54]:
# shape
print(A1.shape)
A1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
print(A2.shape)
A2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [56]:
print(A3.shape)
A3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [57]:
# size
print(A2.size)
A2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [64]:
# itemsize
print(A1.itemsize)
print(A2.itemsize)
print(A3.itemsize)

4
8
4


In [65]:
# dtype
print(A1.dtype)
print(A2.dtype)
print(A3.dtype)

int32
float64
int32


### Changing Datatype

In [66]:
# astype
A1.astype(np.float)

C:\Users\RISHAB~1\AppData\Local\Temp/ipykernel_6164/1218131940.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A1.astype(np.float)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
A2.astype(np.int)

C:\Users\RISHAB~1\AppData\Local\Temp/ipykernel_6164/3868906552.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A2.astype(np.int)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Array Operations

In [68]:
A1 = np.arange(12).reshape(3,4)
A2 = np.arange(12,24).reshape(3,4)

A2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Scalar operations

In [87]:
# arithmetic
A1 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
A1 - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [83]:
A1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [84]:
A1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [88]:
# relational
A1 == 5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [93]:
A2 > 16

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [94]:
A1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
A2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [96]:
A1 + A2 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

#### Vector operations

In [89]:
# arithmetic
A1 ** A2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

### Array Functions

In [98]:
A1 = np.random.random((3,3))
A1 = np.round(A1*100)
A1

array([[18., 14., 71.],
       [ 4., 85., 99.],
       [23., 83., 31.]])

In [100]:
A1.min()

4.0

In [103]:
A1.max()

99.0

In [104]:
A1.sum()

428.0

In [105]:
A1.prod()

35640240284880.0

In [111]:
A2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [114]:
np.max(A2,axis=1) # 0 -> col and 1 -> row

array([15, 19, 23])

In [115]:
np.min(A2,axis=1) # 0 -> col and 1 -> row

array([12, 16, 20])

In [116]:
# 0 -> col and 1 -> row
np.prod(A1,axis=0)

array([  1656.,  98770., 217899.])

In [123]:
A2.mean()
np.mean(A2,axis=1)

array([13.5, 17.5, 21.5])

In [125]:
np.median(A2,axis=1)

array([13.5, 17.5, 21.5])

In [127]:
np.var(A2,axis=1)

array([1.25, 1.25, 1.25])

In [126]:
# trigonomoetric functions
np.sin(A1)

array([[-0.75098725,  0.99060736,  0.95105465],
       [-0.7568025 , -0.17607562, -0.99920683],
       [-0.8462204 ,  0.96836446, -0.40403765]])

In [129]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [131]:
# log and exponents
np.log(A1)

array([[2.89037176, 2.63905733, 4.26267988],
       [1.38629436, 4.44265126, 4.59511985],
       [3.13549422, 4.41884061, 3.4339872 ]])

In [132]:
np.exp(A1)

array([[6.56599691e+07, 1.20260428e+06, 6.83767123e+30],
       [5.45981500e+01, 8.22301271e+36, 9.88903032e+42],
       [9.74480345e+09, 1.11286375e+36, 2.90488497e+13]])

In [134]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[55.,  7., 44.],
       [ 7., 34., 67.]])

In [135]:
np.floor(np.random.random((2,3))*100)

array([[45., 14.,  5.],
       [81.,  8., 53.]])

In [136]:
np.ceil(np.random.random((2,3))*100)

array([[39., 40., 13.],
       [96.,  8., 58.]])

### Indexing and Slicing

In [138]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [139]:
a1
a1[-1]

9

In [141]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
a2[1,2]

6

In [143]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [145]:
a3[0,1,1] 

3

In [148]:
a3[1,0,0]

4

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
a2[1,:]

array([4, 5, 6, 7])

In [151]:
a2[:,2]

array([ 2,  6, 10])

In [172]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [173]:
a2[1::,::2]

array([[ 4,  6],
       [ 8, 10]])

In [182]:
a2[1,0::3]

array([4, 7])

In [185]:
a2[:,2]

array([ 2,  6, 10])

In [186]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [187]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [190]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [193]:
a3[0,1,::]

array([3, 4, 5])

In [196]:
a3[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

In [205]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [207]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [208]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [209]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [210]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [211]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [213]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping

In [214]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [215]:
a3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [216]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [218]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [223]:
np.hstack((a2,a4,a5))

array([[ 0,  1,  2,  3,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11,  8,  9, 10, 11, 20, 21, 22, 23]])

In [224]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [225]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [235]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting

In [229]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [236]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]