In [2]:
import numpy as np
a = np.random.randn(5)

In [3]:
print(a)

[ 0.22961009  1.31571161  0.23891587  0.73646241 -0.8609066 ]


In [5]:
print(a.shape)

(5,)


In [7]:
print(a.T)

[ 0.22961009  1.31571161  0.23891587  0.73646241 -0.8609066 ]


In [8]:
print(np.dot(a,a.T))

3.124435685755074


In [10]:
a = np.random.randn(5,1)
print(a)

[[-0.34715147]
 [-0.66955478]
 [ 1.58095415]
 [-2.59776877]
 [-0.25703226]]


In [11]:
print(a.T)

[[-0.34715147 -0.66955478  1.58095415 -2.59776877 -0.25703226]]


In [13]:
print(np.dot(a,a.T))

[[ 0.12051414  0.23243693 -0.54883056  0.90181925  0.08922913]
 [ 0.23243693  0.44830361 -1.05853541  1.73934851  0.17209718]
 [-0.54883056 -1.05853541  2.49941601 -4.10695331 -0.40635622]
 [ 0.90181925  1.73934851 -4.10695331  6.74840258  0.66771038]
 [ 0.08922913  0.17209718 -0.40635622  0.66771038  0.06606558]]


In [14]:
a = np.random.randn(1,5)
print(a)

[[-0.4004549   1.24761211 -0.74526007 -0.81310308 -1.96621297]]


In [15]:
a = np.random.randn(2,3)
print(a)

[[ 0.06185247 -0.36644479  0.21760156]
 [ 0.27737995 -0.21912652  0.57989636]]


In [16]:
print(a.T)

[[ 0.06185247  0.27737995]
 [-0.36644479 -0.21912652]
 [ 0.21760156  0.57989636]]


In [24]:
a=np.random.randn(2,3) # a.shape = (2, 3)a.shape=(2,3)
b=np.random.randn(2,1) #  b.shape = (2, 1)b.shape=(2,1)

c = a + b 
# c=a+b
d = np.dot(a,b)

# print(c.shape)
print(d.shape)

ValueError: shapes (2,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)

In [28]:
a=np.random.randn(12288,150) # a.shape = (12288, 150)a.shape=(12288,150)
b = np.random.randn(150, 45)
b =np.random.randn(150,45) # b.shape = (150, 45)$$

c = np.dot(a,b)
c=np.dot(a,b) 
print(c.shape)

(12288, 45)


In [32]:
a=np.random.randn(3,3)

b = np.random.randn(3, 1)
b=np.random.randn(3,1)

c = a*b
c=a∗b 

SyntaxError: invalid character '∗' (U+2217) (Temp/ipykernel_14456/736712677.py, line 7)